In [1]:
import pandas as pd
df = pd.read_csv("consumer_complaints.csv")
df

/var/folders/hm/bz_mrxjd62558c4pjvp1b7300000gn/T/ipykernel_98906/3663309967.py:2: DtypeWarning: Columns (0: consumer_complaint_narrative, 1: consumer_consent_provided) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("consumer_complaints.csv")

,date_received,product,sub_product,issue,sub_issue,consumer_complaint_narrative,company_public_response,company,state,zipcode,tags,consumer_consent_provided,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
0,08/30/2013,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,NaN,NaN,U.S. Bancorp,CA,95993,NaN,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511074
1,08/30/2013,Mortgage,Other mortgage,"Loan servicing, payments, escrow account",NaN,NaN,NaN,Wells Fargo & Company,CA,91104,NaN,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511080
2,08/30/2013,Credit reporting,NaN,Incorrect information on credit report,Account status,NaN,NaN,Wells Fargo & Company,NY,11764,NaN,NaN,Postal mail,09/18/2013,Closed with explanation,Yes,No,510473
3,08/30/2013,Student loan,Non-federal student loan,Repaying your loan,Repaying your loan,NaN,NaN,"Navient Solutions, Inc.",MD,21402,NaN,NaN,Email,08/30/2013,Closed with explanation,Yes,Yes,510326
4,08/30/2013,Debt collection,Credit card,False statements or representation,Attempted to collect wrong amount,NaN,NaN,Resurgent Capital Services L.P.,GA,30106,NaN,NaN,Web,08/30/2013,Closed with explanation,Yes,Yes,511067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555952,07/01/2014,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,NaN,NaN,Bank of America,NaN,NaN,NaN,NaN,Referral,07/07/2014,Closed with explanation,Yes,No,919529
555953,07/01/2014,Mortgage,Other mortgage,"Loan servicing, payments, escrow account",NaN,NaN,NaN,Residential Credit Solutions,NaN,NaN,"Older American, Servicemember",NaN,Referral,07/23/2014,Closed with explanation,No,No,918447
555954,07/10/2012,Mortgage,Conventional fixed mortgage,"Loan modification,collection,foreclosure",NaN,NaN,NaN,BB&T Financial,NaN,NaN,NaN,NaN,Phone,11/18/2013,Closed with explanation,Yes,No,114550
555955,04/14/2015,Debt collection,I do not know,Communication tactics,Frequent or repeated calls,NaN,NaN,Global Recovery Group,NaN,NaN,NaN,NaN,Phone,04/14/2015,Untimely response,No,No,1329963
555956,08/14/2014,Debt collection,I do not know,Cont'd attempts collect debt not owed,Debt is not mine,NaN,NaN,"CCS Financial Services, Inc.",NaN,NaN,NaN,NaN,Phone,08/18/2014,Closed with explanation,Yes,No,984116

In [2]:
df.columns

Index(['date_received', 'product', 'sub_product', 'issue', 'sub_issue',
       'consumer_complaint_narrative', 'company_public_response', 'company',
       'state', 'zipcode', 'tags', 'consumer_consent_provided',
       'submitted_via', 'date_sent_to_company', 'company_response_to_consumer',
       'timely_response', 'consumer_disputed?', 'complaint_id'],
      dtype='str')

In [3]:
df.drop(columns=[
    "sub_product",
    "sub_issue",
    "consumer_complaint_narrative",
    "company_public_response",
    "tags",
    "consumer_consent_provided",

], inplace=True)

print(df.columns)

Index(['date_received', 'product', 'issue', 'company', 'state', 'zipcode',
       'submitted_via', 'date_sent_to_company', 'company_response_to_consumer',
       'timely_response', 'consumer_disputed?', 'complaint_id'],
      dtype='str')

In [4]:
df

,date_received,product,issue,company,state,zipcode,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
0,08/30/2013,Mortgage,"Loan modification,collection,foreclosure",U.S. Bancorp,CA,95993,Referral,09/03/2013,Closed with explanation,Yes,Yes,511074
1,08/30/2013,Mortgage,"Loan servicing, payments, escrow account",Wells Fargo & Company,CA,91104,Referral,09/03/2013,Closed with explanation,Yes,Yes,511080
2,08/30/2013,Credit reporting,Incorrect information on credit report,Wells Fargo & Company,NY,11764,Postal mail,09/18/2013,Closed with explanation,Yes,No,510473
3,08/30/2013,Student loan,Repaying your loan,"Navient Solutions, Inc.",MD,21402,Email,08/30/2013,Closed with explanation,Yes,Yes,510326
4,08/30/2013,Debt collection,False statements or representation,Resurgent Capital Services L.P.,GA,30106,Web,08/30/2013,Closed with explanation,Yes,Yes,511067
...,...,...,...,...,...,...,...,...,...,...,...,...
555952,07/01/2014,Mortgage,"Loan modification,collection,foreclosure",Bank of America,NaN,NaN,Referral,07/07/2014,Closed with explanation,Yes,No,919529
555953,07/01/2014,Mortgage,"Loan servicing, payments, escrow account",Residential Credit Solutions,NaN,NaN,Referral,07/23/2014,Closed with explanation,No,No,918447
555954,07/10/2012,Mortgage,"Loan modification,collection,foreclosure",BB&T Financial,NaN,NaN,Phone,11/18/2013,Closed with explanation,Yes,No,114550
555955,04/14/2015,Debt collection,Communication tactics,Global Recovery Group,NaN,NaN,Phone,04/14/2015,Untimely response,No,No,1329963
555956,08/14/2014,Debt collection,Cont'd attempts collect debt not owed,"CCS Financial Services, Inc.",NaN,NaN,Phone,08/18/2014,Closed with explanation,Yes,No,984116

In [5]:
df.columns

Index(['date_received', 'product', 'issue', 'company', 'state', 'zipcode',
       'submitted_via', 'date_sent_to_company', 'company_response_to_consumer',
       'timely_response', 'consumer_disputed?', 'complaint_id'],
      dtype='str')

In [6]:
df.isna().any()

date_received                   False
product                         False
issue                           False
company                         False
state                            True
zipcode                          True
submitted_via                   False
date_sent_to_company            False
company_response_to_consumer    False
timely_response                 False
consumer_disputed?              False
complaint_id                    False
dtype: bool

In [7]:
#df=df.drop(columns=["zipcode"], inplace=True)

In [8]:
#counting how many times each unique state appears in the state column.
df["state"].value_counts()

state
CA    81700
FL    53673
TX    41352
NY    38266
GA    24548
      ...
MH       27
MP       19
AS       17
PW        9
AA        9
Name: count, Length: 62, dtype: int64

In [9]:
#Find the most common state and fill with this
df["state"] = df["state"].fillna(df["state"].mode()[0])
df

,date_received,product,issue,company,state,zipcode,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
0,08/30/2013,Mortgage,"Loan modification,collection,foreclosure",U.S. Bancorp,CA,95993,Referral,09/03/2013,Closed with explanation,Yes,Yes,511074
1,08/30/2013,Mortgage,"Loan servicing, payments, escrow account",Wells Fargo & Company,CA,91104,Referral,09/03/2013,Closed with explanation,Yes,Yes,511080
2,08/30/2013,Credit reporting,Incorrect information on credit report,Wells Fargo & Company,NY,11764,Postal mail,09/18/2013,Closed with explanation,Yes,No,510473
3,08/30/2013,Student loan,Repaying your loan,"Navient Solutions, Inc.",MD,21402,Email,08/30/2013,Closed with explanation,Yes,Yes,510326
4,08/30/2013,Debt collection,False statements or representation,Resurgent Capital Services L.P.,GA,30106,Web,08/30/2013,Closed with explanation,Yes,Yes,511067
...,...,...,...,...,...,...,...,...,...,...,...,...
555952,07/01/2014,Mortgage,"Loan modification,collection,foreclosure",Bank of America,CA,NaN,Referral,07/07/2014,Closed with explanation,Yes,No,919529
555953,07/01/2014,Mortgage,"Loan servicing, payments, escrow account",Residential Credit Solutions,CA,NaN,Referral,07/23/2014,Closed with explanation,No,No,918447
555954,07/10/2012,Mortgage,"Loan modification,collection,foreclosure",BB&T Financial,CA,NaN,Phone,11/18/2013,Closed with explanation,Yes,No,114550
555955,04/14/2015,Debt collection,Communication tactics,Global Recovery Group,CA,NaN,Phone,04/14/2015,Untimely response,No,No,1329963
555956,08/14/2014,Debt collection,Cont'd attempts collect debt not owed,"CCS Financial Services, Inc.",CA,NaN,Phone,08/18/2014,Closed with explanation,Yes,No,984116

In [10]:
df.isna().any()

date_received                   False
product                         False
issue                           False
company                         False
state                           False
zipcode                          True
submitted_via                   False
date_sent_to_company            False
company_response_to_consumer    False
timely_response                 False
consumer_disputed?              False
complaint_id                    False
dtype: bool

In [11]:
df["state"].isna().sum()

np.int64(0)

In [12]:

# Check missing values in state before handling
print("Missing state values before:", df["state"].isna().sum())

Missing state values before: 0

In [13]:
df

,date_received,product,issue,company,state,zipcode,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
0,08/30/2013,Mortgage,"Loan modification,collection,foreclosure",U.S. Bancorp,CA,95993,Referral,09/03/2013,Closed with explanation,Yes,Yes,511074
1,08/30/2013,Mortgage,"Loan servicing, payments, escrow account",Wells Fargo & Company,CA,91104,Referral,09/03/2013,Closed with explanation,Yes,Yes,511080
2,08/30/2013,Credit reporting,Incorrect information on credit report,Wells Fargo & Company,NY,11764,Postal mail,09/18/2013,Closed with explanation,Yes,No,510473
3,08/30/2013,Student loan,Repaying your loan,"Navient Solutions, Inc.",MD,21402,Email,08/30/2013,Closed with explanation,Yes,Yes,510326
4,08/30/2013,Debt collection,False statements or representation,Resurgent Capital Services L.P.,GA,30106,Web,08/30/2013,Closed with explanation,Yes,Yes,511067
...,...,...,...,...,...,...,...,...,...,...,...,...
555952,07/01/2014,Mortgage,"Loan modification,collection,foreclosure",Bank of America,CA,NaN,Referral,07/07/2014,Closed with explanation,Yes,No,919529
555953,07/01/2014,Mortgage,"Loan servicing, payments, escrow account",Residential Credit Solutions,CA,NaN,Referral,07/23/2014,Closed with explanation,No,No,918447
555954,07/10/2012,Mortgage,"Loan modification,collection,foreclosure",BB&T Financial,CA,NaN,Phone,11/18/2013,Closed with explanation,Yes,No,114550
555955,04/14/2015,Debt collection,Communication tactics,Global Recovery Group,CA,NaN,Phone,04/14/2015,Untimely response,No,No,1329963
555956,08/14/2014,Debt collection,Cont'd attempts collect debt not owed,"CCS Financial Services, Inc.",CA,NaN,Phone,08/18/2014,Closed with explanation,Yes,No,984116

In [14]:
# State anusar group by gari complaint_id ko count lai ascending order ma rakhne
state_complaints = df.groupby("state")["complaint_id"].count().sort_values(ascending=True)
state_complaints

state
AA        9
PW        9
AS       17
MP       19
MH       27
      ...
GA    24548
NY    38266
TX    41352
FL    53673
CA    86587
Name: complaint_id, Length: 62, dtype: int64

In [15]:
#state product ra complaints lai groupby
state_product_complaints = df.groupby(["state", "product"])["complaint_id"].count().sort_values(ascending=True)
state_product_complaints

state  product
AA     Bank account or service        1
VI     Student loan                   1
ND     Payday loan                    1
NM     Other financial service        1
MP     Student loan                   1
                                  ...
NY     Mortgage                   11446
CA     Credit reporting           12575
       Debt collection            14272
FL     Mortgage                   20636
CA     Mortgage                   34276
Name: complaint_id, Length: 630, dtype: int64

In [16]:
df.to_csv("consumer_complaints_output.csv", index=False)

In [17]:
state_group = df.groupby("state")

In [18]:
state_group

In [19]:
for state, group in state_group:
    print(state)
    print(group)
    break

AA
       date_received                  product  \
18867     01/07/2014  Bank account or service
80215     06/06/2014             Student loan
93070     05/28/2014                 Mortgage
274347    08/18/2015                 Mortgage
364457    02/20/2013                 Mortgage
374755    04/26/2013                 Mortgage
470760    05/29/2013              Credit card
481426    11/03/2013             Student loan
525503    04/14/2016              Credit card

                                           issue                company state  \
18867    Account opening, closing, or management            Capital One    AA
80215         Dealing with my lender or servicer              AES/PHEAA    AA
93070   Loan servicing, payments, escrow account               Citibank    AA
274347  Loan servicing, payments, escrow account           PHH Mortgage    AA
364457  Loan modification,collection,foreclosure  Wells Fargo & Company    AA
374755  Loan modification,collection,foreclosure  Wells Fargo & Company    AA
470760     Identity theft / Fraud / Embezzlement            Capital One    AA
481426       Problems when you are unable to pay             KeyBank NA    AA
525503                                   Rewards               Discover    AA

       zipcode submitted_via date_sent_to_company  \
18867    34030           Web           01/14/2014
80215    34034           Web           06/06/2014
93070    34058           Web           05/28/2014
274347   340XX           Web           08/18/2015
364457   98282      Referral           02/22/2013
374755   34042           Web           04/29/2013
470760   34041           Web           05/30/2013
481426   73160           Web           11/08/2013
525503   857XX           Web           04/14/2016

       company_response_to_consumer timely_response consumer_disputed?  \
18867       Closed with explanation             Yes                 No
80215       Closed with explanation             Yes                 No
93070       Closed with explanation             Yes                 No
274347      Closed with explanation             Yes                Yes
364457      Closed with explanation             Yes                 No
374755      Closed with explanation             Yes                Yes
470760      Closed with explanation             Yes                 No
481426      Closed with explanation             Yes                 No
525503      Closed with explanation             Yes                Yes

        complaint_id
18867         657556
80215         884195
93070         870620
274347       1524422
364457        322779
374755        392835
470760        418844
481426        582697
525503       1880793

In [20]:
df.groupby("issue")

In [21]:
#groupbyy product,company,complaint
df.groupby(["product", "company"])["complaint_id"].count()

product                  company
Bank account or service  1st Franklin Financial Corporation     1
                         ABC Financial Services, Inc.           1
                         ACE Cash Express Inc.                  6
                         ACS Education Services                 1
                         AES/PHEAA                              3
                                                               ..
Student loan             Wetsch, Abbott & Osborn, PLC           1
                         Williams & Fudge, Inc                 28
                         Windham Professionals                 12
                         Wright & Lerch Attorneys At Law        1
                         Zwicker & Associates                   6
Name: complaint_id, Length: 6420, dtype: int64

In [22]:
df.groupby("state").agg(
    complaints=("complaint_id", "count"),
    companies=("company", "nunique"),
    products=("product", "nunique")
)

       complaints  companies  products
state
AA              9          7         4
AE            219         73         9
AK            638        148        10
AL           5635        554        11
AP            153         61         7
...           ...        ...       ...
VT            943        150        10
WA          11554        702        11
WI           6125        522        11
WV           1457        235        10
WY            551        149        10

[62 rows x 3 columns]

In [23]:
df.groupby("state").size()

state
AA        9
AE      219
AK      638
AL     5635
AP      153
      ...
VT      943
WA    11554
WI     6125
WV     1457
WY      551
Length: 62, dtype: int64

In [24]:
#finds the smallest value in each state.
df.groupby("state")["zipcode"].min()

state
AA    34030
AE     0926
AK     9970
AL    01010
AP    06521
      ...
VT    02857
WA     9837
WI     5313
WV     2531
WY    11111
Name: zipcode, Length: 62, dtype: str

In [25]:
##finds the highest value in each state.
df.groupby("state")["zipcode"].max()

state
AA    98282
AE    236XX
AK    999XX
AL    [36XX
AP    98032
      ...
VT    99352
WA    996XX
WI    99999
WV    82935
WY    98201
Name: zipcode, Length: 62, dtype: str

In [26]:
#number of zipcode in each state
df.groupby("state")["zipcode"].count()

state
AA        9
AE      219
AK      638
AL     5635
AP      153
      ...
VT      943
WA    11553
WI     6125
WV     1457
WY      551
Name: zipcode, Length: 62, dtype: int64

In [27]:
 #different zipcodes
df.groupby("state")["zipcode"].nunique()

state
AA      9
AE     76
AK    124
AL    576
AP     53
     ...
VT    205
WA    589
WI    631
WV    305
WY     93
Name: zipcode, Length: 62, dtype: int64

In [28]:
df

,date_received,product,issue,company,state,zipcode,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
0,08/30/2013,Mortgage,"Loan modification,collection,foreclosure",U.S. Bancorp,CA,95993,Referral,09/03/2013,Closed with explanation,Yes,Yes,511074
1,08/30/2013,Mortgage,"Loan servicing, payments, escrow account",Wells Fargo & Company,CA,91104,Referral,09/03/2013,Closed with explanation,Yes,Yes,511080
2,08/30/2013,Credit reporting,Incorrect information on credit report,Wells Fargo & Company,NY,11764,Postal mail,09/18/2013,Closed with explanation,Yes,No,510473
3,08/30/2013,Student loan,Repaying your loan,"Navient Solutions, Inc.",MD,21402,Email,08/30/2013,Closed with explanation,Yes,Yes,510326
4,08/30/2013,Debt collection,False statements or representation,Resurgent Capital Services L.P.,GA,30106,Web,08/30/2013,Closed with explanation,Yes,Yes,511067
...,...,...,...,...,...,...,...,...,...,...,...,...
555952,07/01/2014,Mortgage,"Loan modification,collection,foreclosure",Bank of America,CA,NaN,Referral,07/07/2014,Closed with explanation,Yes,No,919529
555953,07/01/2014,Mortgage,"Loan servicing, payments, escrow account",Residential Credit Solutions,CA,NaN,Referral,07/23/2014,Closed with explanation,No,No,918447
555954,07/10/2012,Mortgage,"Loan modification,collection,foreclosure",BB&T Financial,CA,NaN,Phone,11/18/2013,Closed with explanation,Yes,No,114550
555955,04/14/2015,Debt collection,Communication tactics,Global Recovery Group,CA,NaN,Phone,04/14/2015,Untimely response,No,No,1329963
555956,08/14/2014,Debt collection,Cont'd attempts collect debt not owed,"CCS Financial Services, Inc.",CA,NaN,Phone,08/18/2014,Closed with explanation,Yes,No,984116

In [29]:
#most common product for each state:
df.groupby("state")["product"].agg(
    lambda x: x.mode().iloc[0]
)

state
AA           Mortgage
AE           Mortgage
AK           Mortgage
AL           Mortgage
AP    Debt collection
           ...
VT           Mortgage
WA           Mortgage
WI           Mortgage
WV           Mortgage
WY           Mortgage
Name: product, Length: 62, dtype: str

In [30]:
#most common issue for each product:
df.groupby("product")["issue"].agg(
    lambda x: x.mode().iloc[0]
)

product
Bank account or service     Account opening, closing, or management
Consumer Loan                            Managing the loan or lease
Credit card                                        Billing disputes
Credit reporting             Incorrect information on credit report
Debt collection               Cont'd attempts collect debt not owed
Money transfers                                       Fraud or scam
Mortgage                   Loan modification,collection,foreclosure
Other financial service                               Fraud or scam
Payday loan                Charged fees or interest I didn't expect
Prepaid card                  Managing, opening, or closing account
Student loan                     Dealing with my lender or servicer
Name: issue, dtype: str

In [31]:
df.groupby("state")["product"].min()

state
AA    Bank account or service
AE    Bank account or service
AK    Bank account or service
AL    Bank account or service
AP    Bank account or service
               ...
VT    Bank account or service
WA    Bank account or service
WI    Bank account or service
WV    Bank account or service
WY    Bank account or service
Name: product, Length: 62, dtype: str

In [32]:
df

,date_received,product,issue,company,state,zipcode,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
0,08/30/2013,Mortgage,"Loan modification,collection,foreclosure",U.S. Bancorp,CA,95993,Referral,09/03/2013,Closed with explanation,Yes,Yes,511074
1,08/30/2013,Mortgage,"Loan servicing, payments, escrow account",Wells Fargo & Company,CA,91104,Referral,09/03/2013,Closed with explanation,Yes,Yes,511080
2,08/30/2013,Credit reporting,Incorrect information on credit report,Wells Fargo & Company,NY,11764,Postal mail,09/18/2013,Closed with explanation,Yes,No,510473
3,08/30/2013,Student loan,Repaying your loan,"Navient Solutions, Inc.",MD,21402,Email,08/30/2013,Closed with explanation,Yes,Yes,510326
4,08/30/2013,Debt collection,False statements or representation,Resurgent Capital Services L.P.,GA,30106,Web,08/30/2013,Closed with explanation,Yes,Yes,511067
...,...,...,...,...,...,...,...,...,...,...,...,...
555952,07/01/2014,Mortgage,"Loan modification,collection,foreclosure",Bank of America,CA,NaN,Referral,07/07/2014,Closed with explanation,Yes,No,919529
555953,07/01/2014,Mortgage,"Loan servicing, payments, escrow account",Residential Credit Solutions,CA,NaN,Referral,07/23/2014,Closed with explanation,No,No,918447
555954,07/10/2012,Mortgage,"Loan modification,collection,foreclosure",BB&T Financial,CA,NaN,Phone,11/18/2013,Closed with explanation,Yes,No,114550
555955,04/14/2015,Debt collection,Communication tactics,Global Recovery Group,CA,NaN,Phone,04/14/2015,Untimely response,No,No,1329963
555956,08/14/2014,Debt collection,Cont'd attempts collect debt not owed,"CCS Financial Services, Inc.",CA,NaN,Phone,08/18/2014,Closed with explanation,Yes,No,984116

In [33]:
df.dtypes

date_received                     str
product                           str
issue                             str
company                           str
state                             str
zipcode                           str
submitted_via                     str
date_sent_to_company              str
company_response_to_consumer      str
timely_response                   str
consumer_disputed?                str
complaint_id                    int64
dtype: object

In [34]:
print(df["zipcode"])

0         95993
1         91104
2         11764
3         21402
4         30106
          ...
555952      NaN
555953      NaN
555954      NaN
555955      NaN
555956      NaN
Name: zipcode, Length: 555957, dtype: str

data transformation

In [35]:
df = df.sort_values("state")
df

,date_received,product,issue,company,state,zipcode,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
274347,08/18/2015,Mortgage,"Loan servicing, payments, escrow account",PHH Mortgage,AA,340XX,Web,08/18/2015,Closed with explanation,Yes,Yes,1524422
481426,11/03/2013,Student loan,Problems when you are unable to pay,KeyBank NA,AA,73160,Web,11/08/2013,Closed with explanation,Yes,No,582697
364457,02/20/2013,Mortgage,"Loan modification,collection,foreclosure",Wells Fargo & Company,AA,98282,Referral,02/22/2013,Closed with explanation,Yes,No,322779
525503,04/14/2016,Credit card,Rewards,Discover,AA,857XX,Web,04/14/2016,Closed with explanation,Yes,Yes,1880793
18867,01/07/2014,Bank account or service,"Account opening, closing, or management",Capital One,AA,34030,Web,01/14/2014,Closed with explanation,Yes,No,657556
...,...,...,...,...,...,...,...,...,...,...,...,...
69393,04/23/2014,Debt collection,Cont'd attempts collect debt not owed,Discover,WY,82935,Web,04/25/2014,Closed with explanation,Yes,No,821399
83377,06/02/2014,Credit reporting,Incorrect information on credit report,"TransUnion Intermediate Holdings, Inc.",WY,82001,Web,06/05/2014,Closed with explanation,Yes,No,876311
546097,01/05/2016,Credit card,Other,Wells Fargo & Company,WY,82501,Web,01/05/2016,Closed with explanation,Yes,No,1728054
431844,01/09/2013,Mortgage,"Loan modification,collection,foreclosure",Bank of America,WY,83118,Referral,01/11/2013,Closed with non-monetary relief,Yes,No,225266
108070,07/21/2014,Mortgage,Settlement process and costs,"Equity National Title and Closing Services, Inc.",WY,82435,Web,07/24/2014,Closed with explanation,No,No,945386

In [44]:
df = df.rename(columns={"product": "PRODUCT"})

print(df.head())

       date_received                  PRODUCT  \
274347    08/18/2015                 MORTGAGE
481426    11/03/2013             STUDENT LOAN
364457    02/20/2013                 MORTGAGE
525503    04/14/2016              CREDIT CARD
18867     01/07/2014  BANK ACCOUNT OR SERVICE

                                           issue                company state  \
274347  Loan servicing, payments, escrow account           PHH Mortgage    AA
481426       Problems when you are unable to pay             KeyBank NA    AA
364457  Loan modification,collection,foreclosure  Wells Fargo & Company    AA
525503                                   Rewards               Discover    AA
18867    Account opening, closing, or management            Capital One    AA

       zipcode submitted_via date_sent_to_company  \
274347   340XX           Web           08/18/2015
481426   73160           Web           11/08/2013
364457   98282      Referral           02/22/2013
525503   857XX           Web           04/14/2016
18867    34030           Web           01/14/2014

       company_response_to_consumer timely_response consumer_disputed?  \
274347      Closed with explanation             Yes                Yes
481426      Closed with explanation             Yes                 No
364457      Closed with explanation             Yes                 No
525503      Closed with explanation             Yes                Yes
18867       Closed with explanation             Yes                 No

        complaint_id
274347       1524422
481426        582697
364457        322779
525503       1880793
18867         657556

In [50]:
#product column values to uppercase:
df["PRODUCT"] = df["PRODUCT"].str.upper()

print(df["PRODUCT"].head())

274347                   MORTGAGE
481426               STUDENT LOAN
364457                   MORTGAGE
525503                CREDIT CARD
18867     BANK ACCOUNT OR SERVICE
Name: PRODUCT, dtype: str

In [49]:
df

,date_received,PRODUCT,issue,company,state,zipcode,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
274347,08/18/2015,MORTGAGE,"Loan servicing, payments, escrow account",PHH Mortgage,AA,340XX,Web,08/18/2015,Closed with explanation,Yes,Yes,1524422
481426,11/03/2013,STUDENT LOAN,Problems when you are unable to pay,KeyBank NA,AA,73160,Web,11/08/2013,Closed with explanation,Yes,No,582697
364457,02/20/2013,MORTGAGE,"Loan modification,collection,foreclosure",Wells Fargo & Company,AA,98282,Referral,02/22/2013,Closed with explanation,Yes,No,322779
525503,04/14/2016,CREDIT CARD,Rewards,Discover,AA,857XX,Web,04/14/2016,Closed with explanation,Yes,Yes,1880793
18867,01/07/2014,BANK ACCOUNT OR SERVICE,"Account opening, closing, or management",Capital One,AA,34030,Web,01/14/2014,Closed with explanation,Yes,No,657556
...,...,...,...,...,...,...,...,...,...,...,...,...
69393,04/23/2014,DEBT COLLECTION,Cont'd attempts collect debt not owed,Discover,WY,82935,Web,04/25/2014,Closed with explanation,Yes,No,821399
83377,06/02/2014,CREDIT REPORTING,Incorrect information on credit report,"TransUnion Intermediate Holdings, Inc.",WY,82001,Web,06/05/2014,Closed with explanation,Yes,No,876311
546097,01/05/2016,CREDIT CARD,Other,Wells Fargo & Company,WY,82501,Web,01/05/2016,Closed with explanation,Yes,No,1728054
431844,01/09/2013,MORTGAGE,"Loan modification,collection,foreclosure",Bank of America,WY,83118,Referral,01/11/2013,Closed with non-monetary relief,Yes,No,225266
108070,07/21/2014,MORTGAGE,Settlement process and costs,"Equity National Title and Closing Services, Inc.",WY,82435,Web,07/24/2014,Closed with explanation,No,No,945386

In [58]:
# 2. Remove extra spaces
df["company"] = df["company"].str.strip()
df.head()

,date_received,PRODUCT,issue,company,state,zipcode,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
274347,08/18/2015,MORTGAGE,"Loan servicing, payments, escrow account",PHH Mortgage,AA,340XX,Web,08/18/2015,Closed with explanation,Yes,Yes,1524422
481426,11/03/2013,STUDENT LOAN,Problems when you are unable to pay,KeyBank NA,AA,73160,Web,11/08/2013,Closed with explanation,Yes,No,582697
364457,02/20/2013,MORTGAGE,"Loan modification,collection,foreclosure",Wells Fargo & Company,AA,98282,Referral,02/22/2013,Closed with explanation,Yes,No,322779
525503,04/14/2016,CREDIT CARD,Rewards,Discover,AA,857XX,Web,04/14/2016,Closed with explanation,Yes,Yes,1880793
18867,01/07/2014,BANK ACCOUNT OR SERVICE,"Account opening, closing, or management",Capital One,AA,34030,Web,01/14/2014,Closed with explanation,Yes,No,657556

In [57]:
df

,date_received,PRODUCT,issue,company,state,zipcode,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
274347,08/18/2015,MORTGAGE,"Loan servicing, payments, escrow account",PHH Mortgage,AA,340XX,Web,08/18/2015,Closed with explanation,Yes,Yes,1524422
481426,11/03/2013,STUDENT LOAN,Problems when you are unable to pay,KeyBank NA,AA,73160,Web,11/08/2013,Closed with explanation,Yes,No,582697
364457,02/20/2013,MORTGAGE,"Loan modification,collection,foreclosure",Wells Fargo & Company,AA,98282,Referral,02/22/2013,Closed with explanation,Yes,No,322779
525503,04/14/2016,CREDIT CARD,Rewards,Discover,AA,857XX,Web,04/14/2016,Closed with explanation,Yes,Yes,1880793
18867,01/07/2014,BANK ACCOUNT OR SERVICE,"Account opening, closing, or management",Capital One,AA,34030,Web,01/14/2014,Closed with explanation,Yes,No,657556
...,...,...,...,...,...,...,...,...,...,...,...,...
69393,04/23/2014,DEBT COLLECTION,Cont'd attempts collect debt not owed,Discover,WY,82935,Web,04/25/2014,Closed with explanation,Yes,No,821399
83377,06/02/2014,CREDIT REPORTING,Incorrect information on credit report,"TransUnion Intermediate Holdings, Inc.",WY,82001,Web,06/05/2014,Closed with explanation,Yes,No,876311
546097,01/05/2016,CREDIT CARD,Other,Wells Fargo & Company,WY,82501,Web,01/05/2016,Closed with explanation,Yes,No,1728054
431844,01/09/2013,MORTGAGE,"Loan modification,collection,foreclosure",Bank of America,WY,83118,Referral,01/11/2013,Closed with non-monetary relief,Yes,No,225266
108070,07/21/2014,MORTGAGE,Settlement process and costs,"Equity National Title and Closing Services, Inc.",WY,82435,Web,07/24/2014,Closed with explanation,No,No,945386

In [60]:
#heck whether every row in the company column has extra spaces at the beginning or end
(df["company"] != df["company"].str.strip()).sum()

np.int64(0)

In [63]:
# . Remove extra spaces from issue
df["issue"] = df["issue"].str.strip()

In [64]:
#heck whether every row in the issue column has extra spaces at the beginning or end
(df["issue"] != df["issue"].str.strip()).sum()

np.int64(0)

In [66]:
# Remove extra spaces from product
df["PRODUCT"] = df["PRODUCT"].str.strip()

In [67]:
#heck whether every row in the product column has extra spaces at the beginning or end
(df["PRODUCT"] != df["PRODUCT"].str.strip()).sum()

np.int64(0)

In [68]:
#heck whether every row in the product column has extra spaces at the beginning or end
(df["company_response_to_consumer"] != df["company_response_to_consumer"].str.strip()).sum()

np.int64(0)

In [62]:
# Check duplicate rows
df.duplicated().sum()

np.int64(0)

In [69]:
# Check empty strings
(df == "").sum()

date_received                   0
PRODUCT                         0
issue                           0
company                         0
state                           0
zipcode                         0
submitted_via                   0
date_sent_to_company            0
company_response_to_consumer    0
timely_response                 0
consumer_disputed?              0
complaint_id                    0
dtype: int64

In [70]:
df.to_csv("consumer_complaints_output.csv", index=False)

np.int64(0)

In [ ]:
# Convert zipcode to integer