In [20]:
import pandas as pd

In [21]:
load_df=pd.read_csv("cleaned.csv")  #importdataframe
print(load_df)  #display all complete dataset

                         title         year certificate duration  \
0               Rick and Morty     (2013– )       TV-MA   23 min
1                 Breaking Bad  (2008–2013)       TV-MA   49 min
2                         1899     (2022– )           0   60 min
3                     Sherlock  (2010–2017)       TV-14   88 min
4   Avatar: The Last Airbender  (2005–2008)    TV-Y7-FV   23 min
..                         ...          ...         ...      ...
74  Avatar: The Last Airbender  (2005–2008)       TV-Y7   22 min
75  Avatar: The Last Airbender  (2005–2008)       TV-Y7   22 min
76                    Top Gear     (2002– )       TV-PG   52 min
77                   Chocolate  (2019–2020)           0        0
78                Breaking Bad  (2008–2013)       TV-MA   49 min

                            genre  rating  \
0    Animation, Adventure, Comedy     9.2
1          Crime, Drama, Thriller     9.5
2          Drama, History, Horror     9.6
3           Crime, Drama, Mystery     9.1
4    Animation, Action, Adventure     9.3
..                            ...     ...
74   Animation, Action, Adventure     9.4
75   Animation, Action, Adventure     9.1
76  Adventure, Comedy, Reality-TV     9.1
77                 Drama, Romance     9.1
78         Crime, Drama, Thriller     9.5

                                          description  \
0   An animated series that follows the exploits o...
1   A high school chemistry teacher diagnosed with...
2   Multinational immigrants traveling from the ol...
3   A modern update finds the famous sleuth and hi...
4   In a war-torn world of elemental magic, a youn...
..                                                ...
74  The invasion seems to be succeeding until Aang...
75  Zuko makes a decision about his future. Aang r...
76  Jeremy, James and Richard each buy a used two-...
77  Making his amends with Kang, Jun reveals a tru...
78  A high school chemistry teacher diagnosed with...

                                                stars      votes
0   ['Justin Roiland, ', 'Chris Parnell, ', 'Spenc...    502,160
1   ['Bryan Cranston, ', 'Aaron Paul, ', 'Anna Gun...  1,831,340
2   ['Ben Ashenden, ', 'Aneurin Barnard, ', 'Emily...        853
3   ['Benedict Cumberbatch, ', 'Martin Freeman, ',...    913,816
4   ['Dee Bradley Baker, ', 'Zach Tyler Eisen, ', ...    309,241
..                                                ...        ...
74  ['Joaquim Dos Santos', '| ', '    Stars:', 'Za...      4,138
75  ['Giancarlo Volpe', '| ', '    Stars:', 'Zach ...      3,856
76  ['James Bryce', '| ', '    Stars:', 'Jeremy Cl...        630
77  ['Lee Hyeong-min', '| ', '    Stars:', 'Ha Ji-...         13
78  ['Bryan Cranston, ', 'Aaron Paul, ', 'Anna Gun...  1,831,359

[79 rows x 9 columns]

In [22]:
load_df.head()  #first five row

,title,year,certificate,duration,genre,rating,description,stars,votes
0,Rick and Morty,(2013– ),TV-MA,23 min,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"['Justin Roiland, ', 'Chris Parnell, ', 'Spenc...","502,160"
1,Breaking Bad,(2008–2013),TV-MA,49 min,"Crime, Drama, Thriller",9.5,A high school chemistry teacher diagnosed with...,"['Bryan Cranston, ', 'Aaron Paul, ', 'Anna Gun...","1,831,340"
2,1899,(2022– ),0,60 min,"Drama, History, Horror",9.6,Multinational immigrants traveling from the ol...,"['Ben Ashenden, ', 'Aneurin Barnard, ', 'Emily...",853
3,Sherlock,(2010–2017),TV-14,88 min,"Crime, Drama, Mystery",9.1,A modern update finds the famous sleuth and hi...,"['Benedict Cumberbatch, ', 'Martin Freeman, ',...","913,816"
4,Avatar: The Last Airbender,(2005–2008),TV-Y7-FV,23 min,"Animation, Action, Adventure",9.3,"In a war-torn world of elemental magic, a youn...","['Dee Bradley Baker, ', 'Zach Tyler Eisen, ', ...","309,241"

title          0
year           0
certificate    0
duration       0
genre          0
rating         0
description    0
stars          0
votes          0
dtype: int64

In [10]:
load_df.head(10)

,title,year,certificate,duration,genre,rating,description,stars,votes
0,Rick and Morty,(2013– ),TV-MA,23 min,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"['Justin Roiland, ', 'Chris Parnell, ', 'Spenc...","502,160"
1,Breaking Bad,(2008–2013),TV-MA,49 min,"Crime, Drama, Thriller",9.5,A high school chemistry teacher diagnosed with...,"['Bryan Cranston, ', 'Aaron Paul, ', 'Anna Gun...","1,831,340"
2,1899,(2022– ),0,60 min,"Drama, History, Horror",9.6,Multinational immigrants traveling from the ol...,"['Ben Ashenden, ', 'Aneurin Barnard, ', 'Emily...",853
3,Sherlock,(2010–2017),TV-14,88 min,"Crime, Drama, Mystery",9.1,A modern update finds the famous sleuth and hi...,"['Benedict Cumberbatch, ', 'Martin Freeman, ',...","913,816"
4,Avatar: The Last Airbender,(2005–2008),TV-Y7-FV,23 min,"Animation, Action, Adventure",9.3,"In a war-torn world of elemental magic, a youn...","['Dee Bradley Baker, ', 'Zach Tyler Eisen, ', ...","309,241"
5,Fullmetal Alchemist: Brotherhood,(2009–2010),TV-14,24 min,"Animation, Action, Adventure",9.1,Two brothers search for a Philosopher's Stone ...,"['Kent Williams, ', 'Iemasa Kayumi, ', 'Matthe...","164,032"
6,The Last Dance,(2020),TV-MA,491 min,"Documentary, Biography, History",9.1,"Charting the rise of the 1990s Chicago Bulls, ...","['Michael Jordan, ', 'Phil Jackson, ', 'Scotti...","119,768"
7,Kota Factory,(2019–2021),TV-14,45 min,"Comedy, Drama",9.1,"Dedicated to Shrimati SL Loney ji, Shri Irodov...","['Mayur More, ', 'Jitendra Kumar, ', 'Ranjan R...","71,138"
8,Cosmos: A Spacetime Odyssey,(2014),TV-PG,557 min,Documentary,9.3,An exploration of our discovery of the laws of...,"['Neil deGrasse Tyson, ', 'Christopher Emerson...","121,400"
9,The Vietnam War,(2017),TV-MA,990 min,"Documentary, History, War",9.1,A comprehensive history of the United States' ...,"['Peter Coyote, ', 'Huy Duc, ', 'James Willban...","24,632"

In [9]:
print(df.head(10))

                              title         year certificate duration  \
0                    Rick and Morty     (2013– )       TV-MA   23 min
1                      Breaking Bad  (2008–2013)       TV-MA   49 min
2                              1899     (2022– )           0   60 min
3                          Sherlock  (2010–2017)       TV-14   88 min
4        Avatar: The Last Airbender  (2005–2008)    TV-Y7-FV   23 min
5  Fullmetal Alchemist: Brotherhood  (2009–2010)       TV-14   24 min
6                    The Last Dance       (2020)       TV-MA  491 min
7                      Kota Factory  (2019–2021)       TV-14   45 min
8       Cosmos: A Spacetime Odyssey       (2014)       TV-PG  557 min
9                   The Vietnam War       (2017)       TV-MA  990 min

                             genre  rating  \
0     Animation, Adventure, Comedy     9.2
1           Crime, Drama, Thriller     9.5
2           Drama, History, Horror     9.6
3            Crime, Drama, Mystery     9.1
4     Animation, Action, Adventure     9.3
5     Animation, Action, Adventure     9.1
6  Documentary, Biography, History     9.1
7                    Comedy, Drama     9.1
8                      Documentary     9.3
9        Documentary, History, War     9.1

                                         description  \
0  An animated series that follows the exploits o...
1  A high school chemistry teacher diagnosed with...
2  Multinational immigrants traveling from the ol...
3  A modern update finds the famous sleuth and hi...
4  In a war-torn world of elemental magic, a youn...
5  Two brothers search for a Philosopher's Stone ...
6  Charting the rise of the 1990s Chicago Bulls, ...
7  Dedicated to Shrimati SL Loney ji, Shri Irodov...
8  An exploration of our discovery of the laws of...
9  A comprehensive history of the United States' ...

                                               stars      votes
0  ['Justin Roiland, ', 'Chris Parnell, ', 'Spenc...    502,160
1  ['Bryan Cranston, ', 'Aaron Paul, ', 'Anna Gun...  1,831,340
2  ['Ben Ashenden, ', 'Aneurin Barnard, ', 'Emily...        853
3  ['Benedict Cumberbatch, ', 'Martin Freeman, ',...    913,816
4  ['Dee Bradley Baker, ', 'Zach Tyler Eisen, ', ...    309,241
5  ['Kent Williams, ', 'Iemasa Kayumi, ', 'Matthe...    164,032
6  ['Michael Jordan, ', 'Phil Jackson, ', 'Scotti...    119,768
7  ['Mayur More, ', 'Jitendra Kumar, ', 'Ranjan R...     71,138
8  ['Neil deGrasse Tyson, ', 'Christopher Emerson...    121,400
9  ['Peter Coyote, ', 'Huy Duc, ', 'James Willban...     24,632

In [11]:
load_df.tail() #display last 5  row

,title,year,certificate,duration,genre,rating,description,stars,votes
74,Avatar: The Last Airbender,(2005–2008),TV-Y7,22 min,"Animation, Action, Adventure",9.4,The invasion seems to be succeeding until Aang...,"['Joaquim Dos Santos', '| ', ' Stars:', 'Za...","4,138"
75,Avatar: The Last Airbender,(2005–2008),TV-Y7,22 min,"Animation, Action, Adventure",9.1,Zuko makes a decision about his future. Aang r...,"['Giancarlo Volpe', '| ', ' Stars:', 'Zach ...","3,856"
76,Top Gear,(2002– ),TV-PG,52 min,"Adventure, Comedy, Reality-TV",9.1,"Jeremy, James and Richard each buy a used two-...","['James Bryce', '| ', ' Stars:', 'Jeremy Cl...",630
77,Chocolate,(2019–2020),0,0,"Drama, Romance",9.1,"Making his amends with Kang, Jun reveals a tru...","['Lee Hyeong-min', '| ', ' Stars:', 'Ha Ji-...",13
78,Breaking Bad,(2008–2013),TV-MA,49 min,"Crime, Drama, Thriller",9.5,A high school chemistry teacher diagnosed with...,"['Bryan Cranston, ', 'Aaron Paul, ', 'Anna Gun...","1,831,359"

In [13]:
load_df.tail(10)  #display last 10 row

,title,year,certificate,duration,genre,rating,description,stars,votes
69,She-Ra and the Princesses of Power,(2018–2020),TV-Y7,24 min,"Animation, Action, Adventure",9.2,Razz confuses the past and the present and has...,"['Mandy Clotworthy', '| ', ' Stars:', 'Aime...","1,184"
70,She-Ra and the Princesses of Power,(2018–2020),TV-Y7,24 min,"Animation, Action, Adventure",9.1,Catra and Hordak fight one another as Glimmer ...,"['Christina Manrique', '| ', ' Stars:', 'Ai...","1,106"
71,The Dragon Prince,(2018– ),TV-Y7,0,"Animation, Action, Adventure",9.4,The human alliance led by King Viren start an ...,"['Villads Spangsberg', '| ', ' Stars:', 'Re...",886
72,Lucifer,(2016–2021),TV-14,61 min,"Crime, Drama, Fantasy",9.3,Chloe learns a serial killer may have embellis...,"['Kevin Alejandro', '| ', ' Stars:', 'Tom E...","5,350"
73,Lucifer,(2016–2021),TV-14,63 min,"Crime, Drama, Fantasy",9.2,Lucifer learns that not all of his siblings wa...,"['Ildy Modrovich', '| ', ' Stars:', 'Tom El...","3,929"
74,Avatar: The Last Airbender,(2005–2008),TV-Y7,22 min,"Animation, Action, Adventure",9.4,The invasion seems to be succeeding until Aang...,"['Joaquim Dos Santos', '| ', ' Stars:', 'Za...","4,138"
75,Avatar: The Last Airbender,(2005–2008),TV-Y7,22 min,"Animation, Action, Adventure",9.1,Zuko makes a decision about his future. Aang r...,"['Giancarlo Volpe', '| ', ' Stars:', 'Zach ...","3,856"
76,Top Gear,(2002– ),TV-PG,52 min,"Adventure, Comedy, Reality-TV",9.1,"Jeremy, James and Richard each buy a used two-...","['James Bryce', '| ', ' Stars:', 'Jeremy Cl...",630
77,Chocolate,(2019–2020),0,0,"Drama, Romance",9.1,"Making his amends with Kang, Jun reveals a tru...","['Lee Hyeong-min', '| ', ' Stars:', 'Ha Ji-...",13
78,Breaking Bad,(2008–2013),TV-MA,49 min,"Crime, Drama, Thriller",9.5,A high school chemistry teacher diagnosed with...,"['Bryan Cranston, ', 'Aaron Paul, ', 'Anna Gun...","1,831,359"

In [14]:
print(df.shape) #check number of rows and column

(79, 9)

In [15]:
print(df.columns) #print columns

Index(['title', 'year', 'certificate', 'duration', 'genre', 'rating',
       'description', 'stars', 'votes'],
      dtype='str')

In [16]:
print(df.dtypes) #check datatype

title              str
year               str
certificate        str
duration           str
genre              str
rating         float64
description        str
stars              str
votes              str
dtype: object

In [17]:
print(df.info())  #get basic information

<class 'pandas.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        79 non-null     str
 1   year         79 non-null     str
 2   certificate  79 non-null     str
 3   duration     79 non-null     str
 4   genre        79 non-null     str
 5   rating       79 non-null     float64
 6   description  79 non-null     str
 7   stars        79 non-null     str
 8   votes        79 non-null     str
dtypes: float64(1), str(8)
memory usage: 5.7 KB
None

In [18]:
#Statistical summary
print(df.describe())

          rating
count  79.000000
mean    9.272152
std     0.178983
min     9.100000
25%     9.100000
50%     9.200000
75%     9.400000
max     9.900000

In [19]:
#tatistical summary including text columns
print(df.describe(include="all"))

                             title         year certificate duration  \
count                           79           79          79       79
unique                          41           33           7       39
top     Avatar: The Last Airbender  (2005–2008)       TV-MA   25 min
freq                            12           12          27       14
mean                           NaN          NaN         NaN      NaN
std                            NaN          NaN         NaN      NaN
min                            NaN          NaN         NaN      NaN
25%                            NaN          NaN         NaN      NaN
50%                            NaN          NaN         NaN      NaN
75%                            NaN          NaN         NaN      NaN
max                            NaN          NaN         NaN      NaN

                               genre     rating  \
count                             79  79.000000
unique                            28        NaN
top     Animation, Action, Adventure        NaN
freq                              24        NaN
mean                             NaN   9.272152
std                              NaN   0.178983
min                              NaN   9.100000
25%                              NaN   9.100000
50%                              NaN   9.200000
75%                              NaN   9.400000
max                              NaN   9.900000

                                              description  \
count                                                  79
unique                                                 78
top     A high school chemistry teacher diagnosed with...
freq                                                    2
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

                                                    stars  votes
count                                                  79     79
unique                                                 70     78
top     ['Ethan Spaulding', '| ', '    Stars:', 'Zach ...  1,184
freq                                                    3      2
mean                                                  NaN    NaN
std                                                   NaN    NaN
min                                                   NaN    NaN
25%                                                   NaN    NaN
50%                                                   NaN    NaN
75%                                                   NaN    NaN
max                                                   NaN    NaN