In [16]:
import pandas as pd
import numpy as np

dict={
    "name":['sita','gita','shyam','alice','bob','kat'],
    "marks":[12,33,56,87,98,90],
    "city":['ktm','pokhara','butwal','lalitpur','bhaktapur','ktm']

}
df=pd.DataFrame(dict)
print(df)
print(type(df))

    name  marks       city
0   sita     12        ktm
1   gita     33    pokhara
2  shyam     56     butwal
3  alice     87   lalitpur
4    bob     98  bhaktapur
5    kat     90        ktm
<class 'pandas.DataFrame'>

DATAFARAME

In [17]:
df.head(2) #top rows

   name  marks     city
0  sita     12      ktm
1  gita     33  pokhara

In [19]:
df.tail(3)  #last rows

    name  marks       city
3  alice     87   lalitpur
4    bob     98  bhaktapur
5    kat     90        ktm

In [20]:
 df.shape   #rows and column

(6, 3)

In [21]:
 df.columns

Index(['name', 'marks', 'city'], dtype='str')

In [28]:
 df.rename(columns={'city':'location'})

    name  marks   location
0   sita     12        ktm
1   gita     33    pokhara
2  shyam     56     butwal
3  alice     87   lalitpur
4    bob     98  bhaktapur
5    kat     90        ktm

In [47]:
df

   Name  Age
0   Ram   22
1  Sita   25
2  Hari   23

In [26]:
 df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      str
 1   marks   6 non-null      int64
 2   city    6 non-null      str
dtypes: int64(1), str(2)
memory usage: 276.0 bytes

In [27]:
df.describe()

           marks
count   6.000000
mean   62.666667
std    34.869280
min    12.000000
25%    38.750000
50%    71.500000
75%    89.250000
max    98.000000

In [170]:
df.to_csv('Test_data.csv')

In [171]:
import os

df.to_csv("Test_data.csv")

print(os.getcwd())

/Users/saritadahal/Desktop/PythonProject/week3

In [35]:
import pandas as pd
import os

data = {
    "Name": ["Ram", "Sita", "Hari"],
    "Age": [22, 25, 23]
}

df = pd.DataFrame(data)

df.to_csv("Test_data.csv", index=False)

print(os.getcwd())

/Users/saritadahal/Desktop/PythonProject/week3

In [45]:
df.to_csv('Test_data.csv', index=False) #export dataframe

In [172]:
load_df=pd.read_csv("Test_data.csv")  #importdataframe
print(load_df)

   Unnamed: 0 Category  Amount  Category_Average  Category_Count
0           0     Food    1200        866.666667               3
1           1     Food     800        866.666667               3
2           2   Travel    2200       1700.000000               2
3           3   Travel    1200       1700.000000               2
4           4     Food     600        866.666667               3

rows and column selection

In [57]:
import pandas as pd
import numpy as np

dict={
    "name":['sita','gita','shyam','alice','bob','kat'],
    "marks":[12,33,56,87,98,90],
    "city":['ktm','pokhara','butwal','lalitpur','bhaktapur','ktm']

}
df=pd.DataFrame(dict)
print(df)
print(type(df))

    name  marks       city
0   sita     12        ktm
1   gita     33    pokhara
2  shyam     56     butwal
3  alice     87   lalitpur
4    bob     98  bhaktapur
5    kat     90        ktm
<class 'pandas.DataFrame'>

In [ ]:
df[['name']]  #single column

In [ ]:
df[['name','city']]  #muntiple column

In [59]:
#select rows
#loc -label based index
df.loc[df.name=='sita']

   name  marks city
0  sita     12  ktm

In [60]:
#iloc index value based
df.iloc[1]

name        gita
marks         33
city     pokhara
Name: 1, dtype: object

In [65]:
#None → missing value
#NaN → missing numerical value
#" Sita " → extra spaces
#"HARI" → inconsistent capitalization
#import pandas as pd

data = {
    "Name": ["Ram", " Sita ", "HARI", None, "Gita"],
    "Age": [22, 25, None, 20, 23],
    "City": ["Kathmandu", "Pokhara", "Kathmandu", None, "Pokhara"],
    "Salary": [30000, 45000, 35000, None, 40000]
}

df = pd.DataFrame(data)

print(df)

     Name   Age       City   Salary
0     Ram  22.0  Kathmandu  30000.0
1   Sita   25.0    Pokhara  45000.0
2    HARI   NaN  Kathmandu  35000.0
3     NaN  20.0        NaN      NaN
4    Gita  23.0    Pokhara  40000.0

In [68]:
  #filter #select a column
print(df["Name"])
print(df[df["Salary"] > 35000])

0       Ram
1     Sita
2      HARI
3       NaN
4      Gita
Name: Name, dtype: str
     Name   Age     City   Salary
1   Sita   25.0  Pokhara  45000.0
4    Gita  23.0  Pokhara  40000.0
     Name   Age     City   Salary
1   Sita   25.0  Pokhara  45000.0
4    Gita  23.0  Pokhara  40000.0

In [69]:
#filter by city
print(df[df["City"] == "Pokhara"])

     Name   Age     City   Salary
1   Sita   25.0  Pokhara  45000.0
4    Gita  23.0  Pokhara  40000.0

In [71]:
#Filter missing values
print(df[df["Age"].isna()])

   Name  Age       City   Salary
2  HARI  NaN  Kathmandu  35000.0

In [72]:
#Find rows where Name is missing
print(df[df["Name"].isna()])

  Name   Age City  Salary
3  NaN  20.0  NaN     NaN

In [75]:
#Filter and select specific columns
print(
    df.loc[df["Salary"] > 35000, ["Name", "Salary"]]
)

     Name   Salary
1   Sita   45000.0
4    Gita  40000.0

In [97]:
#Messy capitalization
df["Name"] = df["Name"].str.strip().str.lower()

print(df)

   Name   Age       City   Salary
0   ram  22.0  Kathmandu  30000.0
1  sita  25.0    Pokhara  45000.0
2  hari   NaN  Kathmandu  35000.0
3   NaN  20.0        NaN      NaN
4  gita  23.0    Pokhara  40000.0

In [98]:
import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Age": [20, None, 22, None],
    "City": ["Kathmandu", "Pokhara", None, "Lalitpur"]
}

df = pd.DataFrame(data)

print("Before:")
print(df)

# Check missing values
print("\nMissing values:")
print(df.isnull().sum())

# Handle missing values
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["City"] = df["City"].fillna("Unknown")

print("\nAfter:")
print(df)

Before:
   Name   Age       City
0   Ram  20.0  Kathmandu
1  Sita   NaN    Pokhara
2  Hari  22.0        NaN
3  Gita   NaN   Lalitpur

Missing values:
Name    0
Age     2
City    1
dtype: int64

After:
   Name   Age       City
0   Ram  20.0  Kathmandu
1  Sita  21.0    Pokhara
2  Hari  22.0    Unknown
3  Gita  21.0   Lalitpur

In [100]:
df.where(df['Age'] >=21)

   Name   Age      City
0   NaN   NaN       NaN
1  Sita  21.0   Pokhara
2  Hari  22.0   Unknown
3  Gita  21.0  Lalitpur

In [103]:
#add new column
df['Team'] = ['student','teacher','ceo','hr']
df

   Name   Age       City     Team
0   Ram  20.0  Kathmandu  student
1  Sita  21.0    Pokhara  teacher
2  Hari  22.0    Unknown      ceo
3  Gita  21.0   Lalitpur       hr

In [109]:
#add new row
df.loc[len(df)] = ['alice','40','butwal','principal']
df

    Name   Age       City       Team
0    Ram  20.0  Kathmandu    student
1   Sita  21.0    Pokhara    teacher
2   Hari  22.0    Unknown        ceo
3   Gita  21.0   Lalitpur         hr
4  alice    40     butwal  principal
5  alice    40     butwal  principal
6  alice    40     butwal  principal
7  alice    40     butwal  principal
8  alice    40     butwal  principal
9  alice    40     butwal  principal

In [111]:
#update value using index name
df.loc[4,'team'] ='cto'
df

    Name   Age       City       Team team
0    Ram  20.0  Kathmandu    student  NaN
1   Sita  21.0    Pokhara    teacher  NaN
2   Hari  22.0    Unknown        ceo  NaN
3   Gita  21.0   Lalitpur         hr  NaN
4  alice    40     butwal  principal  cto
5  alice    40     butwal  principal  NaN
6  alice    40     butwal  principal  NaN
7  alice    40     butwal  principal  NaN
8  alice    40     butwal  principal  NaN
9  alice    40     butwal  principal  NaN

In [115]:
#update value usingolumn value
df.loc[df["Name"] == "sita", "Age"] = 25
df

    Name   Age       City       Team team  age
0    Ram  20.0  Kathmandu    student  NaN  NaN
1   Sita  21.0    Pokhara    teacher  NaN  NaN
2   Hari  22.0    Unknown        ceo  NaN  NaN
3   Gita  21.0   Lalitpur         hr  NaN  NaN
4  alice    40     butwal  principal  cto  NaN
5  alice    40     butwal  principal  NaN  NaN
6  alice    40     butwal  principal  NaN  NaN
7  alice    40     butwal  principal  NaN  NaN
8  alice    40     butwal  principal  NaN  NaN
9  alice    40     butwal  principal  NaN  NaN

In [116]:
 #delete row
 df.drop(df[df["Name"] == "alice"].index)

   Name   Age       City     Team team  age
0   Ram  20.0  Kathmandu  student  NaN  NaN
1  Sita  21.0    Pokhara  teacher  NaN  NaN
2  Hari  22.0    Unknown      ceo  NaN  NaN
3  Gita  21.0   Lalitpur       hr  NaN  NaN

In [128]:
#drop column
df.drop('age' , axis=1,inplace = True)

df

    Name   Age       City
0    Ram  20.0  Kathmandu
1   Sita  21.0    Pokhara
2   Hari  22.0    Unknown
3   Gita  21.0   Lalitpur
4  alice    40     butwal
5  alice    40     butwal
6  alice    40     butwal
7  alice    40     butwal
8  alice    40     butwal
9  alice    40     butwal

In [134]:
#drop by name

df.drop(df[df["Name"] == "alice"].index)

    Name   Age       City
3   Gita  21.0   Lalitpur
2   Hari  22.0    Unknown
0    Ram  20.0  Kathmandu
1   Sita  21.0    Pokhara
4  alice    40     butwal
5  alice    40     butwal
6  alice    40     butwal
7  alice    40     butwal
8  alice    40     butwal
9  alice    40     butwal

In [140]:
# Sort by Name
df = df.sort_values("Name")

# Remove duplicate Names
df = df.drop_duplicates(subset=["Name"])

print(df)

    Name   Age       City
3   Gita  21.0   Lalitpur
2   Hari  22.0    Unknown
0    Ram  20.0  Kathmandu
1   Sita  21.0    Pokhara
4  alice    40     butwal

In [146]:
#sort
df["Name"] = df["Name"].str.lower()
df = df.sort_values("Name")

print(df)

    Name   Age       City
4  alice    40     butwal
3   gita  21.0   Lalitpur
2   hari  22.0    Unknown
0    ram  20.0  Kathmandu
1   sita  21.0    Pokhara

In [147]:
import pandas as pd

data = {
    "Category": ["Food", "Food", "Travel", "Travel", "Food"],
    "Amount": [500, 300, 1000, 500, 200]
}

df = pd.DataFrame(data)

print(df)

  Category  Amount
0     Food     500
1     Food     300
2   Travel    1000
3   Travel     500
4     Food     200

aggregation,

In [148]:
#group by category and sum
result = df.groupby("Category")["Amount"].sum()

print(result)

Category
Food      1000
Travel    1500
Name: Amount, dtype: int64

In [150]:
#count
print(df["Amount"].value_counts())

Amount
500     2
300     1
1000    1
200     1
Name: count, dtype: int64

In [151]:
#count by number
df[df['Amount']==500].value_counts()

Category  Amount
Food      500       1
Travel    500       1
Name: count, dtype: int64

In [152]:
#total
total = df["Amount"].sum()

print("Total:", total)

Total: 2500

In [153]:
#average
average = df["Amount"].mean()

print("Average:", average)

Average: 500.0

In [154]:
#highest
highest = df["Amount"].max()

print("Highest:", highest)

Highest: 1000

In [155]:
#lowest
lowest = df["Amount"].min()

print("Lowest:", lowest)

Lowest: 200

In [156]:
#count amount
count = df["Amount"].count()

print("Count:", count)

Count: 5

In [158]:
#All aggregations together
result = df["Amount"].agg(["sum", "mean", "max", "min", "count"])

print(result)

sum      2500.0
mean      500.0
max      1000.0
min       200.0
count       5.0
Name: Amount, dtype: float64

grouping

In [160]:
#aggegation based on group by
df.groupby('Category')['Amount'].mean()

Category
Food      333.333333
Travel    750.000000
Name: Amount, dtype: float64

In [161]:
#group and calculate total
result = df.groupby("Category")["Amount"].sum()

print(result)

Category
Food      1000
Travel    1500
Name: Amount, dtype: int64

In [162]:
#group and calculate category
result = df.groupby("Category").size()

print(result)

Category
Food      3
Travel    2
dtype: int64

In [163]:
##group and calculate amount
result = df.groupby("Amount").size()

print(result)

Amount
200     1
300     1
500     2
1000    1
dtype: int64

transformation

In [164]:
#dd 100 to every Amount
df["Amount"] = df["Amount"].transform(lambda x: x + 100)

print(df)

  Category  Amount
0     Food     600
1     Food     400
2   Travel    1100
3   Travel     600
4     Food     300

In [165]:
#Convert Amount to double
df["Amount"] = df["Amount"].transform(lambda x: x * 2)

print(df)

  Category  Amount
0     Food    1200
1     Food     800
2   Travel    2200
3   Travel    1200
4     Food     600

In [166]:
#Group + Transformation
df["Category_Average"] = df.groupby("Category")["Amount"].transform("mean")

print(df)

  Category  Amount  Category_Average
0     Food    1200        866.666667
1     Food     800        866.666667
2   Travel    2200       1700.000000
3   Travel    1200       1700.000000
4     Food     600        866.666667

In [169]:
#Group + transform with count
df["Category_Count"] = df.groupby("Category")["Amount"].transform("count")

print(df)

  Category  Amount  Category_Average  Category_Count
0     Food    1200        866.666667               3
1     Food     800        866.666667               3
2   Travel    2200       1700.000000               2
3   Travel    1200       1700.000000               2
4     Food     600        866.666667               3