In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('consumer_complaints.csv')

/var/folders/hm/bz_mrxjd62558c4pjvp1b7300000gn/T/ipykernel_94790/3141106651.py:1: DtypeWarning: Columns (0: consumer_complaint_narrative, 1: consumer_consent_provided) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('consumer_complaints.csv')

In [22]:
df.head()

,date_received,product,sub_product,issue,sub_issue,consumer_complaint_narrative,company_public_response,company,state,zipcode,tags,consumer_consent_provided,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
0,08/30/2013,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,NaN,NaN,U.S. Bancorp,CA,95993,NaN,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511074
1,08/30/2013,Mortgage,Other mortgage,"Loan servicing, payments, escrow account",NaN,NaN,NaN,Wells Fargo & Company,CA,91104,NaN,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511080
2,08/30/2013,Credit reporting,NaN,Incorrect information on credit report,Account status,NaN,NaN,Wells Fargo & Company,NY,11764,NaN,NaN,Postal mail,09/18/2013,Closed with explanation,Yes,No,510473
3,08/30/2013,Student loan,Non-federal student loan,Repaying your loan,Repaying your loan,NaN,NaN,"Navient Solutions, Inc.",MD,21402,NaN,NaN,Email,08/30/2013,Closed with explanation,Yes,Yes,510326
4,08/30/2013,Debt collection,Credit card,False statements or representation,Attempted to collect wrong amount,NaN,NaN,Resurgent Capital Services L.P.,GA,30106,NaN,NaN,Web,08/30/2013,Closed with explanation,Yes,Yes,511067

In [23]:
print(df.shape)

(555957, 18)

In [24]:
print(df.columns)

Index(['date_received', 'product', 'sub_product', 'issue', 'sub_issue',
       'consumer_complaint_narrative', 'company_public_response', 'company',
       'state', 'zipcode', 'tags', 'consumer_consent_provided',
       'submitted_via', 'date_sent_to_company', 'company_response_to_consumer',
       'timely_response', 'consumer_disputed?', 'complaint_id'],
      dtype='str')

In [25]:
print(df.dtypes)

date_received                     str
product                           str
sub_product                       str
issue                             str
sub_issue                         str
consumer_complaint_narrative      str
company_public_response           str
company                           str
state                             str
zipcode                           str
tags                              str
consumer_consent_provided         str
submitted_via                     str
date_sent_to_company              str
company_response_to_consumer      str
timely_response                   str
consumer_disputed?                str
complaint_id                    int64
dtype: object

In [26]:
#*****************************
print(df.isnull().sum())

date_received                        0
product                              0
sub_product                     158322
issue                                0
sub_issue                       343335
consumer_complaint_narrative    489151
company_public_response         470833
company                              0
state                             4887
zipcode                           4505
tags                            477998
consumer_consent_provided       432499
submitted_via                        0
date_sent_to_company                 0
company_response_to_consumer         0
timely_response                      0
consumer_disputed?                   0
complaint_id                         0
dtype: int64

In [27]:
df.drop(columns=["sub_issue"], inplace=True)

In [28]:
df.head()

,date_received,product,sub_product,issue,consumer_complaint_narrative,company_public_response,company,state,zipcode,tags,consumer_consent_provided,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
0,08/30/2013,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,NaN,U.S. Bancorp,CA,95993,NaN,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511074
1,08/30/2013,Mortgage,Other mortgage,"Loan servicing, payments, escrow account",NaN,NaN,Wells Fargo & Company,CA,91104,NaN,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511080
2,08/30/2013,Credit reporting,NaN,Incorrect information on credit report,NaN,NaN,Wells Fargo & Company,NY,11764,NaN,NaN,Postal mail,09/18/2013,Closed with explanation,Yes,No,510473
3,08/30/2013,Student loan,Non-federal student loan,Repaying your loan,NaN,NaN,"Navient Solutions, Inc.",MD,21402,NaN,NaN,Email,08/30/2013,Closed with explanation,Yes,Yes,510326
4,08/30/2013,Debt collection,Credit card,False statements or representation,NaN,NaN,Resurgent Capital Services L.P.,GA,30106,NaN,NaN,Web,08/30/2013,Closed with explanation,Yes,Yes,511067

In [29]:
df.shape

(555957, 17)

In [30]:
print(df.isnull().sum()[df.isnull().sum() > 0])

sub_product                     158322
consumer_complaint_narrative    489151
company_public_response         470833
state                             4887
zipcode                           4505
tags                            477998
consumer_consent_provided       432499
dtype: int64

In [31]:
df=df.dropna(subset=["state"], inplace=True)

In [33]:
#number of NULL values for only the columns that actually have NULL values.
#columns that have missing values:
print(df.isnull().sum()[df.isnull().sum() > 0])

AttributeError: 'NoneType' object has no attribute 'isnull'

In [34]:
df.zipcode.value_counts()

AttributeError: 'NoneType' object has no attribute 'zipcode'

In [35]:
test = df[df["state"] == "GA"]["zipcode"].value_counts()

TypeError: 'NoneType' object is not subscriptable

In [361]:
test.head()

zipcode
300XX    1202
303XX     589
302XX     471
301XX     415
30349     323
Name: count, dtype: int64

In [362]:
df.index[0]

AttributeError: 'NoneType' object has no attribute 'index'

In [363]:
df[df["state"] == "GA"]["zipcode"].value_counts().index[0]

TypeError: 'NoneType' object is not subscriptable

In [365]:
df

In [366]:
def fill_zipcode(row, df):
    if pd.isna(row["zipcode"]):
        state_data = df[df["state"] == row["state"]]
        return state_data["zipcode"].mode().iloc[0]
    return row["zipcode"]

df["zipcode"] = df.apply(fill_zipcode, axis=1, df=df)

AttributeError: 'NoneType' object has no attribute 'apply'

In [367]:
df[df["zipcode"].isna()].apply(fill_zipcode, axis=1, df=df)

TypeError: 'NoneType' object is not subscriptable

In [369]:
for row in df[df["zipcode"].isna()]:
    pass

TypeError: 'NoneType' object is not subscriptable

In [370]:
print(df.isnull().sum(axis=1))

AttributeError: 'NoneType' object has no attribute 'isnull'

In [371]:
#get a general summary
print(df.info())

AttributeError: 'NoneType' object has no attribute 'info'

In [372]:
df.drop(columns=["tags"])
df

AttributeError: 'NoneType' object has no attribute 'drop'

In [373]:
df.shape

AttributeError: 'NoneType' object has no attribute 'shape'

In [374]:
print(df.isnull().sum())

AttributeError: 'NoneType' object has no attribute 'isnull'

In [375]:
df.drop(columns=["tags"])

AttributeError: 'NoneType' object has no attribute 'drop'

In [225]:
df = df.drop(columns=["sub_issue", "consumer_complaint_narrative", "company_public_response","consumer_consent_provided"])
df

KeyError: "['sub_issue'] not found in axis"

In [376]:
df.shape

AttributeError: 'NoneType' object has no attribute 'shape'

In [377]:
df[df.isna().any(axis=1)]
df

AttributeError: 'NoneType' object has no attribute 'isna'

In [378]:
print(df.columns.tolist())  #title name

AttributeError: 'NoneType' object has no attribute 'columns'

In [230]:
print("Before:", "tags" in df.columns)

df.drop(columns=["tags"], errors="ignore", inplace=True)

print("After:", "tags" in df.columns)

Before: False
After: False

In [231]:
print(df.isnull().sum())

date_received                        0
product                              0
sub_product                     157119
issue                                0
consumer_complaint_narrative    484450
company_public_response         466659
company                              0
state                                0
zipcode                              0
consumer_consent_provided       428016
submitted_via                        0
date_sent_to_company                 0
company_response_to_consumer         0
timely_response                      0
consumer_disputed?                   0
complaint_id                         0
dtype: int64

In [232]:
df[df.isna().any(axis=1)]
df

,date_received,product,sub_product,issue,consumer_complaint_narrative,company_public_response,company,state,zipcode,consumer_consent_provided,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
0,08/30/2013,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,NaN,U.S. Bancorp,CA,95993,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511074
1,08/30/2013,Mortgage,Other mortgage,"Loan servicing, payments, escrow account",NaN,NaN,Wells Fargo & Company,CA,91104,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511080
2,08/30/2013,Credit reporting,NaN,Incorrect information on credit report,NaN,NaN,Wells Fargo & Company,NY,11764,NaN,Postal mail,09/18/2013,Closed with explanation,Yes,No,510473
3,08/30/2013,Student loan,Non-federal student loan,Repaying your loan,NaN,NaN,"Navient Solutions, Inc.",MD,21402,NaN,Email,08/30/2013,Closed with explanation,Yes,Yes,510326
4,08/30/2013,Debt collection,Credit card,False statements or representation,NaN,NaN,Resurgent Capital Services L.P.,GA,30106,NaN,Web,08/30/2013,Closed with explanation,Yes,Yes,511067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553092,03/23/2016,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,NaN,Bank of America,NJ,080XX,NaN,Web,03/31/2016,In progress,Yes,No,1846137
553093,03/31/2016,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,Company has responded to the consumer and the ...,U.S. Bancorp,OH,44647,NaN,Referral,04/04/2016,Closed with explanation,Yes,No,1859306
553094,03/08/2016,Mortgage,Conventional fixed mortgage,"Loan servicing, payments, escrow account",NaN,NaN,Dovenmuehle Mortgage Inc.,CO,802XX,NaN,Web,03/08/2016,Closed with explanation,Yes,No,1822445
553095,03/28/2016,Mortgage,Other mortgage,"Loan servicing, payments, escrow account",NaN,Company has responded to the consumer and the ...,Wells Fargo & Company,PA,17236,NaN,Referral,03/31/2016,Closed with explanation,Yes,No,1852707
553096,02/12/2016,Mortgage,Conventional fixed mortgage,"Application, originator, mortgage broker",Bank of America has demonstrated an on-going l...,Company has responded to the consumer and the ...,Bank of America,GA,300XX,Consent provided,Web,02/12/2016,Closed with explanation,Yes,Yes,1786225

In [233]:
df.isna().sum()

date_received                        0
product                              0
sub_product                     157119
issue                                0
consumer_complaint_narrative    484450
company_public_response         466659
company                              0
state                                0
zipcode                              0
consumer_consent_provided       428016
submitted_via                        0
date_sent_to_company                 0
company_response_to_consumer         0
timely_response                      0
consumer_disputed?                   0
complaint_id                         0
dtype: int64

In [234]:
df.isna()

,date_received,product,sub_product,issue,consumer_complaint_narrative,company_public_response,company,state,zipcode,consumer_consent_provided,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
0,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False,False
2,False,False,True,False,True,True,False,False,False,True,False,False,False,False,False,False
3,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False,False
4,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553092,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False,False
553093,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False
553094,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False,False
553095,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False
553096,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [235]:
print(df.isnull())

        date_received  product  sub_product  issue  \
0               False    False        False  False
1               False    False        False  False
2               False    False         True  False
3               False    False        False  False
4               False    False        False  False
...               ...      ...          ...    ...
553092          False    False        False  False
553093          False    False        False  False
553094          False    False        False  False
553095          False    False        False  False
553096          False    False        False  False

        consumer_complaint_narrative  company_public_response  company  state  \
0                               True                     True    False  False
1                               True                     True    False  False
2                               True                     True    False  False
3                               True                     True    False  False
4                               True                     True    False  False
...                              ...                      ...      ...    ...
553092                          True                     True    False  False
553093                          True                    False    False  False
553094                          True                     True    False  False
553095                          True                    False    False  False
553096                         False                    False    False  False

        zipcode  consumer_consent_provided  submitted_via  \
0         False                       True          False
1         False                       True          False
2         False                       True          False
3         False                       True          False
4         False                       True          False
...         ...                        ...            ...
553092    False                       True          False
553093    False                       True          False
553094    False                       True          False
553095    False                       True          False
553096    False                      False          False

        date_sent_to_company  company_response_to_consumer  timely_response  \
0                      False                         False            False
1                      False                         False            False
2                      False                         False            False
3                      False                         False            False
4                      False                         False            False
...                      ...                           ...              ...
553092                 False                         False            False
553093                 False                         False            False
553094                 False                         False            False
553095                 False                         False            False
553096                 False                         False            False

        consumer_disputed?  complaint_id
0                    False         False
1                    False         False
2                    False         False
3                    False         False
4                    False         False
...                    ...           ...
553092               False         False
553093               False         False
553094               False         False
553095               False         False
553096               False         False

[551070 rows x 16 columns]

In [236]:
#chehck missing value
print(df.isnull())

        date_received  product  sub_product  issue  \
0               False    False        False  False
1               False    False        False  False
2               False    False         True  False
3               False    False        False  False
4               False    False        False  False
...               ...      ...          ...    ...
553092          False    False        False  False
553093          False    False        False  False
553094          False    False        False  False
553095          False    False        False  False
553096          False    False        False  False

        consumer_complaint_narrative  company_public_response  company  state  \
0                               True                     True    False  False
1                               True                     True    False  False
2                               True                     True    False  False
3                               True                     True    False  False
4                               True                     True    False  False
...                              ...                      ...      ...    ...
553092                          True                     True    False  False
553093                          True                    False    False  False
553094                          True                     True    False  False
553095                          True                    False    False  False
553096                         False                    False    False  False

        zipcode  consumer_consent_provided  submitted_via  \
0         False                       True          False
1         False                       True          False
2         False                       True          False
3         False                       True          False
4         False                       True          False
...         ...                        ...            ...
553092    False                       True          False
553093    False                       True          False
553094    False                       True          False
553095    False                       True          False
553096    False                      False          False

        date_sent_to_company  company_response_to_consumer  timely_response  \
0                      False                         False            False
1                      False                         False            False
2                      False                         False            False
3                      False                         False            False
4                      False                         False            False
...                      ...                           ...              ...
553092                 False                         False            False
553093                 False                         False            False
553094                 False                         False            False
553095                 False                         False            False
553096                 False                         False            False

        consumer_disputed?  complaint_id
0                    False         False
1                    False         False
2                    False         False
3                    False         False
4                    False         False
...                    ...           ...
553092               False         False
553093               False         False
553094               False         False
553095               False         False
553096               False         False

[551070 rows x 16 columns]

In [237]:
import pandas as pd

df = pd.read_csv("consumer_complaints.csv")

grouped = df.groupby("state").size()

print(grouped)

/var/folders/hm/bz_mrxjd62558c4pjvp1b7300000gn/T/ipykernel_83906/1641556734.py:3: DtypeWarning: Columns (0: consumer_complaint_narrative, 1: consumer_consent_provided) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("consumer_complaints.csv")

state
AA        9
AE      219
AK      638
AL     5635
AP      153
      ...
VT      943
WA    11554
WI     6125
WV     1457
WY      551
Length: 62, dtype: int64

In [238]:
#groupby highest to lowest
state_complaints = df.groupby("state")["complaint_id"].count().sort_values(ascending=False)

print(state_complaints)

state
CA    81700
FL    53673
TX    41352
NY    38266
GA    24548
      ...
MH       27
MP       19
AS       17
PW        9
AA        9
Name: complaint_id, Length: 62, dtype: int64

In [239]:
#state+product
df.groupby(["state", "product"]).size()

state  product
AA     Bank account or service      1
       Credit card                  2
       Mortgage                     4
       Student loan                 2
AE     Bank account or service     21
                                 ...
WY     Money transfers              1
       Mortgage                   151
       Other financial service      1
       Payday loan                  8
       Student loan                23
Length: 630, dtype: int64

In [240]:
#zipcode+complaint_id
df.groupby("zipcode")["complaint_id"].count()

zipcode
 0106    1
 0160    1
 0236    1
 0288    2
 0611    1
        ..
[9507    2
`1195    1
`2285    1
`29XX    1
`3290    1
Name: complaint_id, Length: 27052, dtype: int64

In [241]:
df.groupby(["zipcode", "product"]).size()

zipcode  product
 0106    Credit card                1
 0160    Mortgage                   1
 0236    Bank account or service    1
 0288    Money transfers            1
         Mortgage                   1
                                   ..
[9507    Mortgage                   2
`1195    Consumer Loan              1
`2285    Mortgage                   1
`29XX    Mortgage                   1
`3290    Bank account or service    1
Length: 102053, dtype: int64

In [266]:
df

In [267]:
print(df.isnull().sum())

AttributeError: 'NoneType' object has no attribute 'isnull'

In [264]:
df.drop(columns=["tags"])

AttributeError: 'NoneType' object has no attribute 'drop'

In [265]:
df

In [263]:
df.drop(columns=["tags"])

AttributeError: 'NoneType' object has no attribute 'drop'

In [252]:
df = df.drop(columns=["tags"])

KeyError: "['tags'] not found in axis"

In [254]:
df=df.drop(columns=["zipcode"])

In [255]:
df=df.drop(columns=["sub_product"])

,date_received,product,issue,sub_issue,consumer_complaint_narrative,company_public_response,company,state,consumer_consent_provided,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
0,08/30/2013,Mortgage,"Loan modification,collection,foreclosure",NaN,NaN,NaN,U.S. Bancorp,CA,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511074
1,08/30/2013,Mortgage,"Loan servicing, payments, escrow account",NaN,NaN,NaN,Wells Fargo & Company,CA,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511080
2,08/30/2013,Credit reporting,Incorrect information on credit report,Account status,NaN,NaN,Wells Fargo & Company,NY,NaN,Postal mail,09/18/2013,Closed with explanation,Yes,No,510473
3,08/30/2013,Student loan,Repaying your loan,Repaying your loan,NaN,NaN,"Navient Solutions, Inc.",MD,NaN,Email,08/30/2013,Closed with explanation,Yes,Yes,510326
4,08/30/2013,Debt collection,False statements or representation,Attempted to collect wrong amount,NaN,NaN,Resurgent Capital Services L.P.,GA,NaN,Web,08/30/2013,Closed with explanation,Yes,Yes,511067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555952,07/01/2014,Mortgage,"Loan modification,collection,foreclosure",NaN,NaN,NaN,Bank of America,NaN,NaN,Referral,07/07/2014,Closed with explanation,Yes,No,919529
555953,07/01/2014,Mortgage,"Loan servicing, payments, escrow account",NaN,NaN,NaN,Residential Credit Solutions,NaN,NaN,Referral,07/23/2014,Closed with explanation,No,No,918447
555954,07/10/2012,Mortgage,"Loan modification,collection,foreclosure",NaN,NaN,NaN,BB&T Financial,NaN,NaN,Phone,11/18/2013,Closed with explanation,Yes,No,114550
555955,04/14/2015,Debt collection,Communication tactics,Frequent or repeated calls,NaN,NaN,Global Recovery Group,NaN,NaN,Phone,04/14/2015,Untimely response,No,No,1329963
555956,08/14/2014,Debt collection,Cont'd attempts collect debt not owed,Debt is not mine,NaN,NaN,"CCS Financial Services, Inc.",NaN,NaN,Phone,08/18/2014,Closed with explanation,Yes,No,984116

In [258]:
df=df.drop(columns=[
    "sub_issue",
    "sub_product",
    "consumer_complaint_narrative",
    "consumer_consent_provided",
], inplace=True)
df

AttributeError: 'NoneType' object has no attribute 'drop'

In [262]:
print(df)

None